---
# This Playbook runs all the common plays in the deployment 

- name: Create /etc/environment 
  copy: src=environment dest=/etc/environment

- name: create locale.gen
  template: src=templates/locale.gen.j2 dest=/etc/locale.gen
  when_boolean: $lang
  notify:
    - update locale-gen
  tags:
    - locale

- name: configure locale (with UTF-8 charset)
  template: src=templates/locale.j2 dest=/etc/default/locale
  when_boolean: $lang
  notify:
    - update locale
  tags:
    - locale

#- name: Create the hosts file for all machines
#  template: src=hosts.j2 dest=/etc/hosts

#- name: Create the repository for 10Gen  
#  copy: src=10gen.repo.j2 dest=/etc/yum.repos.d/10gen.repo

#- name: Create the apt repo for 10gen
#  apt_repository: repo='deb deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' 
#                  state=present

#- name: Add 10gen apt key
#  apt_key: id=7F0CEB10 url=keyserver.ubuntu.com state=present

#- name: Create the EPEL Repository.
#  copy: src=epel.repo.j2 dest=/etc/yum.repos.d/epel.repo

#- name: Create the GPG key for EPEL
#  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg

- name: Create the mongod user
  user: name=mongod comment="MongoD"

- name: Create the mongodb user
  user: name=mongodb comment="MongoDB"

- name: Create the data directory for the namenode metadata
  file: path={{ mongodb_datadir_prefix }} owner=mongodb group=mongodb state=directory

#- name: Install the mongodb package
#  apt: name={{ item }} state=installed
#  with_items:
#   - mongo-10gen
#   - mongo-10gen-server
#   - bc
#   - python-pip

- name: Install mongodb
  apt: pkg=mongodb
  retries: 5
  delay: 60

- name: Install mongodb-server
  apt: pkg=mongodb-server

- name: Install bc
  apt: pkg=bc

- name: Install python-pip
  apt: pkg=python-pip

- name: Install the latest pymongo package
  pip: name=pymongo state=latest use_mirrors=no 

#- name: Create the iptables file
#  template: src=iptables.j2 dest=/etc/sysconfig/iptables
#  notify: restart iptables 
